const orgCharityImages = [
  //
  [
    "AFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/ADELAIDE-CROWS-768x277.jpg",
  ],
  [
    "BL",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/BRISBANE-LIONS-768x277.jpg",
  ],
  [
    "CFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/CARLTON-B-768x282.jpg",
    "Carlton Blues", // optional if there are more than 1
  ],
  [
    "CFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/COLLINGWOOD-768x282.jpg",
    "Collingwood Magpies", // optional if there are more than 1
  ],
  [
    "EFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/ESSENDON-A-768x282.jpg",
  ],
  [
    "FD",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/FREO-DOCKERS-B-768x277.jpg",
  ],
  [
    "GFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/GEELONG-768x277.jpg",
  ],
  [
    "HFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/HAWTHORN-HAWKS-768x277.jpg",
  ],
  [
    "MFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/MELBOURNE-768x290.jpg",
    "Melbourne Football Club",
  ],
  [
    "ROO",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/NORTH-MELB-768x277.jpg",
  ],
  [
    "PORT",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/PORT-POWER-A-768x290.jpg",
  ],
  [
    "RFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/RICHMOND-768x277.jpg",
  ],
  [
    "SKS",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/SAINT-KILDA-768x277.jpg",
  ],
  [
    "SFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/SYDNEY-SWANS-768x277.jpg",
  ],
  // [
  //   "WCE",
  //   "org_charity",
  //   "https://www.waaflplates.com.au/wp-content/uploads/2022/06/WEST-COAST-EAGLES-A-768x277.jpg",
  // ],
  [
    "WBFC",
    "org_charity",
    "https://www.waaflplates.com.au/wp-content/uploads/2022/06/WESTERN-BULLDOGS-A-768x277.jpg",
  ],

  [
    "CAT",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wacat2019.jpg",
  ],
  [
    "DFC",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-177368-kl.gif",
  ],
  [
    "FD",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wafreemantledockers2020.jpg",
  ],
  [
    "FSC",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-188201-kl.gif",
  ],
  [
    "GBYC",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-44038-kl.gif",
  ],
  [
    "GCS",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wageraldtonspwy.jpg",
  ],
  [
    "GSP",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-188214-kl.gif",
  ],
  [
    "NFC",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wanorthamptonfc.jpg",
  ],
  [
    "PAW",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-188219-kl.gif",
  ],
  [
    "PG",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-188298-kl.gif",
  ],
  [
    "PMH",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-74020-kl.gif",
  ],
  [
    "RCS",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/warottnest.jpg",
  ],
  [
    "RFCA",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/warailwaysfooty2018.jpg",
  ],
  [
    "RNC",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wesrausnavyclub.jpg",
  ],
  [
    "SPYC",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-188311-kl.gif",
  ],
  [
    "SSRL",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wasouthsyd.jpg",
  ],
  [
    "VFF",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wavff.jpg",
  ],
  [
    "WAC",
    "org_charity",
    "http://www.plate-planet.com/images/plates/Fotobatch-188258-kl.gif",
  ],
  [
    "WBFC",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wabulldogs2021.jpg",
  ],
  [
    "WCE",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wawestcoasteagle.jpg",
  ],
  [
    "WFC",
    "org_charity",
    "http://www.plateshack.com/y2k/Western_Australia/wawatherloofc.jpg",
    "Watheroo Football Club", // optional if there are more than 1
  ],
];

const townShireImages = [
  [
    "HRP",
    "town_shire",
    "http://www.plate-planet.com/images/plates/Fotobatch-79455-kl.gif",
  ],
  [
    "GOS",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wesausgosnells2021.jpg",
  ],
  [
    "NAT",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wacape2017.jpg",
  ],
  [
    "AW",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/washirearthur.jpg",
  ],
  [
    "COW",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wacowramup.jpg",
  ],
  [
    "CRJ",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wa2021clackline.jpg",
  ],
  [
    "IR",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/washireirwin.jpg",
  ],
  [
    "K",
    "town_shire",
    "https://warego.au/wp-content/uploads/2019/06/shire-council-2.png",
  ],
  [
    "KUK",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wakukerin.jpg",
  ],
  [
    "KUK",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wanungarin.jpg",
  ],
  [
    "NGT",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wanewmachinery.jpg",
  ],
  [
    "ONG",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/waongerup.jpg",
  ],
  [
    "PL",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/waplantegenetshire.jpg",
  ],
  [
    "TS",
    "town_shire",
    "http://www.plateshack.com/y2k/Western_Australia/wa2021threesprings.jpg",
  ],
  [
    "VPK",
    "town_shire",
    "http://www.plate-planet.com/images/plates/Fotobatch-188144-kl.gif",
  ],
  [
    "VP",
    "town_shire",
    "http://www.plate-planet.com/images/plates/Fotobatch-160286-kl.gif",
  ],
  [
    "W",
    "town_shire",
    "http://www.plate-planet.com/images/plates/Fotobatch-65224-kl.gif",
  ],
  [
    "WA",
    "town_shire",
    "http://www.plate-planet.com/images/plates/Fotobatch-188148-kl.gif",
  ],
];

const roadDistrictImages = [
  [
    "AK",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-160002-kl.gif",
  ],
  [
    "AL",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/waalbany.jpg",
  ],
  [
    "AS",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-188004-kl.gif",
  ],
  [
    "BE",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wabeverley.jpg",
  ],
  [
    "C",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-159247-kl.gif",
  ],
  [
    "CB",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-188047-kl.gif",
  ],
  [
    "CM",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wa2016CM1416.jpg",
  ],
  [
    "DB",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/westaustralia.JPG",
  ],
  [
    "DE",
    "road_district",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/1990s_Western_Australia_Regional_Plate%2C_89_DE%2C_Denmark.jpg/200px-1990s_Western_Australia_Regional_Plate%2C_89_DE%2C_Denmark.jpg",
  ],
  [
    "GN",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wabatavia2021.jpg", // this is (withoutdot) greraldton
    "Geraldton (without dot)",
  ],
  [
    "JP",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wasoldier.jpg",
  ],
  [
    "KBC",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/au-wakalgoorlie.jpg",
  ],
  [
    "L",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/waleeonora.jpg",
  ],
  [
    "M",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wamoorashire.jpg",
  ],
  [
    "MDG",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/westausmundaring.jpg",
  ],
  [
    "PJ",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wa,peronjori.jpg",
  ],
  [
    "SJ",
    "road_district",
    "http://www.plateshack.com/y2k/Western_Australia/wa2016-SJ4643.jpg",
  ],
  [
    "WB",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-160300-kl.gif",
  ],
  [
    "WK",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-160307-kl.gif",
  ],
  [
    "WL",
    "road_district",
    "http://www.plate-planet.com/images/plates/Fotobatch-160324-kl.gif",
  ],
  [
    "Y",
    "road_district",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/2000_Western_Australia_registration_plate_Y%E2%80%A26642_York.jpg/200px-2000_Western_Australia_registration_plate_Y%E2%80%A26642_York.jpg",
  ],
];

module.exports = [
  ...orgCharityImages,
  ...townShireImages,
  ...roadDistrictImages,
];
